update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -111,14 +111,15 @@ echo ""
 echo -e "\x1B[32mOptimLib Configuration\033[0m" >&2 ;
 echo ""
 
-# look for Armadillo
+declare -a OPTIM_MATLIB_DIRS=("${WDIR}/../../include" "/usr/include" "/usr/local/include" "/opt/include" "/opt/local/include")
+
+# look for linear algebra library header files
 if [[ "${OPTIM_LINEAR_ALG_LIB}" == "arma" ]]; then
     if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
         
-        declare -a ARMA_DIRS=("${WDIR}/../../include" "/usr/include" "/usr/local/include" "/opt/include" "/opt/local/include")
         ARMA_INCLUDE_PATH=
 
-        for i in "${ARMA_DIRS[@]}"; do
+        for i in "${OPTIM_MATLIB_DIRS[@]}"; do
             if [ -f "$i"/armadillo ]; then 
                 ARMA_INCLUDE_PATH="$i"
                 break
@@ -126,7 +127,9 @@ if [[ "${OPTIM_LINEAR_ALG_LIB}" == "arma" ]]; then
         done
 
         if [[ $ARMA_INCLUDE_PATH == "" ]]; then
-            echo -e "  \x1B[31m- error: cannot find the Armadillo library header files. Exiting.\033[0m" >&2 ;
+            echo -e "  \x1B[31m- error: cannot find the Armadillo library header files.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Please set the ARMA_INCLUDE_PATH environment variable.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Exiting.\033[0m" >&2 ;
             echo ""
             exit 1
         fi
@@ -143,6 +146,26 @@ elif [[ "${OPTIM_LINEAR_ALG_LIB}" == "blaze" ]]; then
     echo ""
     exit 1
 elif [[ "${OPTIM_LINEAR_ALG_LIB}" == "eigen" ]]; then
+    if [ -z ${EIGEN_INCLUDE_PATH+x} ]; then 
+        
+        EIGEN_INCLUDE_PATH=
+
+        for i in "${OPTIM_MATLIB_DIRS[@]}"; do
+            if [ -f "$i"/Eigen ]; then 
+                EIGEN_INCLUDE_PATH="$i"
+                break
+            fi
+        done
+
+        if [[ $EIGEN_INCLUDE_PATH == "" ]]; then
+            echo -e "  \x1B[31m- error: cannot find the Eigen library header files.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Please set the EIGEN_INCLUDE_PATH environment variable.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Exiting.\033[0m" >&2 ;
+            echo ""
+            exit 1
+        fi
+    fi
+
     OPTIM_MATLIB_FLAGS="-DOPTIM_ENABLE_EIGEN_WRAPPERS"
     OPTIM_MATLIB_INCLUDE_PATH=$EIGEN_INCLUDE_PATH
 else
diff --git a/tests/test_setup/configure.in b/tests/test_setup/configure.in
--- a/tests/test_setup/configure.in
+++ b/tests/test_setup/configure.in
@@ -54,14 +54,15 @@ APPLE_COMPILER=$($CXX --version 2>&1 | grep -i -c -E 'apple llvm')
 # get working directory
 WDIR=${PWD}
 
+declare -a OPTIM_MATLIB_DIRS=("${WDIR}/../../include" "/usr/include" "/usr/local/include" "/opt/include" "/opt/local/include")
+
 # look for Armadillo
 if [[ "${OPTIM_LINEAR_ALG_LIB}" == "arma" ]]; then
     if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
         
-        declare -a ARMA_DIRS=("${WDIR}/../../include" "/usr/include" "/usr/local/include" "/opt/include" "/opt/local/include")
         ARMA_INCLUDE_PATH=
 
-        for i in "${ARMA_DIRS[@]}"; do
+        for i in "${OPTIM_MATLIB_DIRS[@]}"; do
             if [ -f "$i"/armadillo ]; then 
                 ARMA_INCLUDE_PATH="$i"
                 break
@@ -69,7 +70,9 @@ if [[ "${OPTIM_LINEAR_ALG_LIB}" == "arma" ]]; then
         done
 
         if [[ $ARMA_INCLUDE_PATH == "" ]]; then
-            echo -e "  \x1B[31m- error: cannot find the Armadillo library header files. Exiting.\033[0m" >&2 ;
+            echo -e "  \x1B[31m- error: cannot find the Armadillo library header files.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Please set the ARMA_INCLUDE_PATH environment variable.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Exiting.\033[0m" >&2 ;
             echo ""
             exit 1
         fi
@@ -86,6 +89,26 @@ elif [[ "${OPTIM_LINEAR_ALG_LIB}" == "blaze" ]]; then
     echo ""
     exit 1
 elif [[ "${OPTIM_LINEAR_ALG_LIB}" == "eigen" ]]; then
+    if [ -z ${EIGEN_INCLUDE_PATH+x} ]; then 
+        
+        EIGEN_INCLUDE_PATH=
+
+        for i in "${OPTIM_MATLIB_DIRS[@]}"; do
+            if [ -f "$i"/Eigen ]; then 
+                EIGEN_INCLUDE_PATH="$i"
+                break
+            fi
+        done
+
+        if [[ $EIGEN_INCLUDE_PATH == "" ]]; then
+            echo -e "  \x1B[31m- error: cannot find the Eigen library header files.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Please set the EIGEN_INCLUDE_PATH environment variable.\033[0m" >&2 ;
+            echo -e "  \x1B[31m         Exiting.\033[0m" >&2 ;
+            echo ""
+            exit 1
+        fi
+    fi
+
     OPTIM_MATLIB_FLAGS="-DOPTIM_ENABLE_EIGEN_WRAPPERS"
     OPTIM_MATLIB_INCLUDE_PATH=$EIGEN_INCLUDE_PATH
 else
